# -*- coding: utf-8 -*-
"""ASSIGMENT AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qTt8z-JSpY2Tjvoz-Xd4A26ExeLf4tEj
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import math
from scipy.optimize import differential_evolution, minimize

# Load dataset
df = pd.read_csv("/content/drive/MyDrive/Vignesh tr/xy_data.csv")
x_obs = df['x'].values
y_obs = df['y'].values
t = np.linspace(6, 60, len(df))  # assume uniform t

# Parametric model
def model_xy(t, theta_rad, M, X):
    s = np.sin(0.3 * t)
    e = np.exp(M * np.abs(t))
    x = t * np.cos(theta_rad) - e * s * np.sin(theta_rad) + X
    y = 42 + t * np.sin(theta_rad) + e * s * np.cos(theta_rad)
    return x, y

# L1 loss function
def l1_loss(params):
    theta_rad, M, X = params
    xm, ym = model_xy(t, theta_rad, M, X)
    return np.mean(np.abs(x_obs - xm) + np.abs(y_obs - ym))

# Parameter bounds
deg_lo, deg_hi = 0, 50
th_lo, th_hi = math.radians(deg_lo), math.radians(deg_hi)
bounds = [(th_lo, th_hi), (-0.05, 0.05), (0, 100)]

# Global optimization
result = differential_evolution(l1_loss, bounds, strategy='best1bin', maxiter=400, popsize=18, tol=1e-7)
best = result.x

# Local refinement
res = minimize(l1_loss, best, method='Nelder-Mead')
theta_rad, M, X = res.x
theta_deg = math.degrees(theta_rad)

print("Final Fitted Values:")
print(f"Theta (deg): {theta_deg}")
print(f"M: {M}")
print(f"X: {X}")